### PR TITLE
build(windows): fix issue with GCC specific pragmas

### LINKED ISSUE #97: build(windows): unknown pragmas before spline library include
### Description
Compiling on Windows with `msbuild` produces lots of warnings for unknown pragmas in `Interpolator.h`. These pragmas are used when building with `gcc` or `clang` to disable warnings from the external (header only) spline calculation library.

### Steps To Reproduce
1. Build on Windows with `msbuild`.
2. Warnings for unknown pragmas.

### Expected Behaviour
No warnings about unknown pragmas. 
No warnings caused by external spline library.

### Possible Steps To Fix
- [x] Check if the compiler is `gcc` or `clang` and only use those pragmas in that case.
- [x] Find suitable alternative pragmas for `msvc` compilation which disable the same warnings.

### Environment
```
os:        Windows 11
compiler:  msvc
```

### PR DESCRIPTION
**Pull request by t-bre**
## Description

- Pragmas before inclusion of `spline.h` are now done using JUCE macros.
- Pragmas disabled unless they actually exist with the current compiler.
- Prevents issues when compiling with MSVC.
- Tested build on a VM, so not 100% sure if this definitely works, needs review.

Closes #97 

## Checklist

- [x] Code linted with `trunk check`
- [x] Code formatted with `trunk fmt`
- [x] Changes do not generate any new compiler warnings
- [x] Commit messages follow the [Conventional Commits Specification](https://www.conventionalcommits.org/en/v1.0.0/#specification)

### CODE REVIEW

**Comment by t-bre** [comment]
Needs tested by a Windows user not running a VM

**Comment by t-bre** [comment]
@niketa282 could you test this and see if the "unknown pragma" related warnings are gone?
It should now only use pragmas if they match the compiler, and hopefully the MSVC pragmas are correct and there are no warnings from the spline library.

Alternatively, if you know how to add ignored warnings for all instances of spline.h with CMake and not pragmas that would be a much better way to do this.

**Review by niketa282 — APPROVED** [review]
LGTM!
There is one oddity though if I delete the build directory, create a new build directory and then configure with CMake and run the msbuild ./VCU-GUI.sln it gives me the warnings, but if I clear the output and rerun the msbuild command the next time the warnings disappear

**Comment by t-bre** [comment]
> There is one oddity though if I delete the build directory, create a new build directory and then configure with CMake and run the msbuild ./VCU-GUI.sln it gives me the warnings, but if I clear the output and rerun the msbuild command the next time the warnings disappear

To me that suggests that the issue hasn't been fixed. Could you paste the part of the output with the warnings? 

The reason you get it when you build the first time but not the second is because of the build caching - the file hasn't changed and (I think) you haven't cleaned the build directory, so the file is not re-compiled and no warnings are produced. That's how it works with `make` at least, not 100% sure about `msbuild` but I'd guess it's the same.

We should possibly set `-Werror` (and equivalent for `msvc`) to prevent warnings from being lost/hidden in this way. Any serious warnings should be caught by the linter, but I still think it's a good idea?

**Comment by niketa282** [comment]
> Nevermind, found the issue! Should have looked closer at the logs and `spline.h` - the header itself has some GCC specific pragmas but doesn't actually check which compiler is being used. So its not any of our code that is causing the warning.
> 
> I suggest we add `4068` to the ignored warnings for MSVC, since there isn't much else we can do. We could fork spline and add a fix, but I think we can just ignore the warning since the pragma just gets ignored by the compiler.

Just to see if I understood you, does this mean adding this #pragma NotAValidPragmaName before
 #pragma GCC diagnostic push?

**Comment by t-bre** [comment]
> Just to see if I understood you, does this mean adding this #pragma NotAValidPragmaName before #pragma GCC diagnostic push?

Not exactly sure what you mean. Are you referring to [this example](https://learn.microsoft.com/mt-mt/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4068?view=msvc-160)?

4068 is the MSVC compiler warning for 'unknown pragma' which is happening at the lines in the spline header starting with `#pragma GCC`. All I meant was to use the JUCE macro to temporarily ignore the warning for the unknown pragma when building with MSVC. We can do that by adding `4068` to the existing list of ignored warnings for the spline header:

```cpp
JUCE_BEGIN_IGNORE_WARNINGS_MSVC(4267 4068)
```



I think that will fix the warnings, but again sorry I can't test it without a Windows machine!

**Comment by niketa282** [comment]
> > Just to see if I understood you, does this mean adding this #pragma NotAValidPragmaName before #pragma GCC diagnostic push?
> 
> Not exactly sure what you mean. Are you referring to [this example](https://learn.microsoft.com/mt-mt/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4068?view=msvc-160)?
> 
> 4068 is the MSVC compiler warning for 'unknown pragma' which is happening at the lines in the spline header starting with `#pragma GCC`. All I meant was to use the JUCE macro to temporarily ignore the warning for the unknown pragma when building with MSVC. We can do that by adding `4068` to the existing list of ignored warnings for the spline header:
> 
> ```c++
> JUCE_BEGIN_IGNORE_WARNINGS_MSVC(4267 4068)
> ```
> 
> (the ignore warning macros are used in `Interpolator.h` which is the only file that includes `spline.h`)
> 
> I've just pushed the change I was describing and I think that will sort the warnings, but again sorry I can't test it without a Windows machine!



> > Just to see if I understood you, does this mean adding this #pragma NotAValidPragmaName before #pragma GCC diagnostic push?
> 
> Not exactly sure what you mean. Are you referring to [this example](https://learn.microsoft.com/mt-mt/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4068?view=msvc-160)?
> 
> 4068 is the MSVC compiler warning for 'unknown pragma' which is happening at the lines in the spline header starting with `#pragma GCC`. All I meant was to use the JUCE macro to temporarily ignore the warning for the unknown pragma when building with MSVC. We can do that by adding `4068` to the existing list of ignored warnings for the spline header:
> 
> ```c++
> JUCE_BEGIN_IGNORE_WARNINGS_MSVC(4267 4068)
> ```
> 
> (the ignore warning macros are used in `Interpolator.h` which is the only file that includes `spline.h`)
> 
> I've just pushed the change I was describing and I think that will sort the warnings, but again sorry I can't test it without a Windows machine!

yes I was referring to that example, I assumed you could add that pragma in spline.h and it would work, but I don't know much about this so I understand what you mean now after seeing the latest commit. 

Yup it gets rid of the gcc warnings so that's good.

Now its only left with 4 warnings, but maybe different PR for that? 

`  C:\Users\hp\Documents\niketa\vcu-gui\src\gui\appearance\LookAndFeel.cpp(43,22): warning C4244: 'initializing': conversion from 'int' to 'float', possi 
ble loss of data [C:\Users\hp\Documents\niketa\vcu-gui\build\VCU-GUI.vcxproj]
  C:\Users\hp\Documents\niketa\vcu-gui\src\gui\appearance\LookAndFeel.cpp(44,19): warning C4244: 'initializing': conversion from 'int' to 'float', possi 
ble loss of data [C:\Users\hp\Documents\niketa\vcu-gui\build\VCU-GUI.vcxproj]
  C:\Users\hp\Documents\niketa\vcu-gui\src\gui\components\MainComponent.cpp(117,58): warning C4100: 'redirectedTree': unreferenced formal parameter [C:\ 
Users\hp\Documents\niketa\vcu-gui\build\VCU-GUI.vcxproj]`

**Pull request merged**
